apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-post-microservice-blogs
  labels:
    app: blog-post-microservice-blogs
spec:
  # destination:
  #   namespace: default
  replicas: 1
  selector:
    matchLabels:
      app: blog-post-microservice-blogs
  template:
    metadata:
      labels:
        app: blog-post-microservice-blogs
    spec:
      containers:
        - name: blog-post-microservice-blogs
          image: nadir24950/blog-post-microservice-blogs:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://nadir24950:1ITd5ynQ@cluster0.hcif53s.mongodb.net/?retryWrites=true&w=majority"
          ports:
            - containerPort: 3030
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 10
          #   periodSeconds: 15
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 20
          #   periodSeconds: 25
