apiVersion: v1
kind: Service
metadata:
  name: blog-post-microservice-frontend
spec:
  type: NodePort
  selector:
    app: blog-post-microservice-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
